CIP-35: Add paragraph explaining replay protection through EIP-155
celo-org/celo-proposals pull request #174
Opened 2021-02-25 21:51 UTC by oneeman

This adds a paragraph to CIP-35 clarifying that Celo and Ethereum both have replay-protection through EIP-155, so that any individual signed transaction is specific to one chain and can't later also be used on the other chain.

2021-02-25 21:55 UTC, prestwich requested changes
It's not accurate to say that a tx is never valid for both. Users can opt out of using EIP-155 and create replayable txns.

Is the network id correct? I thought it was 52752 (0xCE10)

2021-02-25 21:56 UTC, prestwich commented
> 52752 (0xCE10)

Huh. Just looked it up. This is the slip44 designation. I didn't know it was different from the network id

2021-02-25 22:39 UTC, oneeman commented
> It's not accurate to say that a tx is never valid for both. Users can opt out of using EIP-155 and create replayable txns.
> 
> Is the chain id correct? I thought it was 52752 (0xCE10)

My bad, I didn't notice it was `SHOULD` in EIP-155.  Do any/many Ethereum wallets expose ways to opt out of EIP-155?  I'm wondering how it should be phrased given that this actually is a possibility.

2021-02-25 22:47 UTC, oneeman commented
Actually, looking at the code, it appears Celo has never supported non-EIP155 transactions (though you could create a Celo testnet supporting it, but mainnet, alfajores, and baklava never supported it).  I will double-check.

2021-02-25 22:51 UTC, prestwich commented
> Actually, looking at the code, it appears Celo has never supported non-EIP155 transactions (though you could create a Celo testnet supporting it, but mainnet, alfajores, and baklava never supported it). I will double-check.

Very interesting. Might be good to update the language to call this out specifically, as it is a departure from expected behavior

in practice, nobody opts out

2021-02-25 22:58 UTC, oneeman commented
> > Actually, looking at the code, it appears Celo has never supported non-EIP155 transactions (though you could create a Celo testnet supporting it, but mainnet, alfajores, and baklava never supported it). I will double-check.
> 
> Very interesting. Might be good to update the language to call this out specifically, as it is a departure from expected behavior
> 
> in practice, nobody opts out

Actually, I spoke too soon based on the signer used being the EIP155 signer.  But of course when it comes to signature verification the signer supports verifying non-EIP155 signatures as well.

2021-02-26 14:29 UTC, oneeman commented
@prestwich Updated the EIP-155 section, please have a look.

2021-02-26 16:48 UTC, prestwich approved these changes

2021-02-26 16:48 UTC, prestwich commented
LGTM

2021-03-02 16:38 UTC, merged