CIP 2: Professional Verifier Pool
celo-org/celo-proposals pull request #2
Opened 2019-08-24 22:02 UTC by nambrot

In the early prototypes of the [lightweight identity protocol](https://docs.celo.org/celo-codebase/protocol/identity), Celo had a concept of a verifier app. It would send text messages on behalf of the protocol and would receive a share of the attestation fee revenue. It was a truly permissionless on-ramp. However, over discussions, we had sybil and game-theoretic concerns over the viability of that scheme. This CIP proposes a return of the verifier app in the context of a professionally run text message provider that uses verifier apps to send the message. In this scheme, the provider has a reputation to uphold and acts as a possible alternative to providers like Twilio.

2020-05-12 18:36 UTC, asaj commented
@nambrot can we close?

2020-05-15 14:09 UTC, nambrot commented
I'd say this CIP is still open so I'd actually argue we should merge it as a draft?

2020-11-10 16:56 UTC, YazzyYaz requested changes

2020-11-10 16:56 UTC, YazzyYaz commented on CIPs/0002.md
> +# CIP 2: Professional Verifier Pool
Please ensure your title follows the new cip-template.md file.

Also ensure status is Draft.

https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-template.md

Also please ensure the rest of the document headings are following the new CIP template document. Abstract, Simple Summary, Motivation, Rationale, Specification, CopyRight, Implementation, etc.

2020-11-10 16:56 UTC, YazzyYaz commented on CIPs/0002.md
> +### Alternative Solution
I'd like to see this whole document following the new template so we can have consistency.

2020-12-01 19:40 UTC, prestwich requested changes
To be merged please:
1. Update to follow the new template
2. Open a discussions issue `CIP 2 - Professional Verifier Pool - Discussions`
3. Update the discussions-to link in the new template header

2020-12-01 22:25 UTC, nambrot commented
I'll close as not relevant

2020-12-01 22:25 UTC, closed without merging