Add CGP-37, Contracts Release 5
celo-org/celo-proposals pull request #271
Opened 2021-08-13 16:32 UTC by m-chrzan

2021-08-13 17:36 UTC, yorhodes approved these changes

2021-08-13 17:36 UTC, yorhodes commented on CGPs/0037.md
> +Changes that are being proposed in this release are described in [this Github release](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v5.pre-audit).
```suggestion
Changes that are being proposed in this release are described in [this Github release](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v5).
```

2021-08-13 17:36 UTC, yorhodes commented on CGPs/0037.md
> +* [Github release](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v5.pre-audit)
```suggestion
* [Github release](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v5)
```

2021-08-16 13:19 UTC, YazzyYaz requested changes
Please submit to the new governance repo. 

CGPs are being removed from this repo. see https://github.com/celo-org/celo-proposals/pull/264

2021-08-16 17:27 UTC, yorhodes commented
https://github.com/celo-org/governance/pull/16 @YazzyYaz

2021-08-16 17:27 UTC, closed without merging