Governable Loopback Window (CIP-0021)
celo-org/celo-proposals pull request #48
Opened 2020-09-28 13:11 UTC by andres-dg

2020-11-10 17:40 UTC, YazzyYaz requested changes

2020-11-10 17:40 UTC, YazzyYaz commented on CIPs/0021.md
> +- Author: @andres-dg
hi @andres-dg  thank you for submitting this CIP, I would like you to update it to follow the newly activated CIP process which has it's newly updated template here: https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-template.md

Also, if the CIP is in Draft status, I'd be able to merge the proposal into the repo after the other action items are completed.

2020-11-12 15:54 UTC, YazzyYaz reviewed
I'd also add to rename the file to cip-0021.md

Once you do that and add the link for discussions, I'll approve the PR for a Draft

2020-11-12 15:54 UTC, YazzyYaz commented on CIPs/0021.md
> +discussions-to: <to be assigned>
please create a github issue for your proposal called "Discussions for Governable Lookback Window"

2020-11-18 18:21 UTC, prestwich approved these changes

2020-11-18 18:22 UTC, prestwich commented
This will need more specification after merging as a draft

2020-11-18 18:59 UTC, YazzyYaz commented on CIPs/0021.md
> +discussions-to: <to be assigned>
@andres-dg just made it for you https://github.com/celo-org/celo-proposals/issues/86

2020-11-18 19:01 UTC, YazzyYaz approved these changes

2020-11-18 19:01 UTC, merged